spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: http://httpbin.org:80/get
          predicates:
#            - After=2019-01-20T17:42:47.789-07:00[America/Denver]
#             - Header=X-Request-Id, \d+
#            - Cookie=name, forezp
#            - Host=**.xrf.com
#            - Method=GET

#              - Path=/foo/{segment}
              - Query=foo, ba.
  profiles: after_route
